import type { EventData } from "./types"

// Sample events data for April 2025
export const EVENTS_DATA: EventData = {
  "2025-04-01": [
    {
      id: "1",
      title: "Ads Campaign Nr/2",
      date: new Date(2025, 3, 1),
      startTime: "09:00",
      endTime: "17:00",
      color: "yellow",
      description: "AdSense + FB, Target Audience",
    },
  ],
  "2025-04-02": [
    {
      id: "2",
      title: "Ads Campaign Nr/2",
      date: new Date(2025, 3, 2),
      startTime: "09:00",
      endTime: "17:00",
      color: "yellow",
      description: "AdSense + FB, Target Audience",
    },
    {
      id: "3",
      title: "Team Meeting",
      date: new Date(2025, 3, 2),
      startTime: "14:00",
      endTime: "15:00",
      color: "blue",
      description: "Weekly team sync",
    },
    {
      id: "4",
      title: "Client Call",
      date: new Date(2025, 3, 2),
      startTime: "16:00",
      endTime: "17:00",
      color: "green",
      description: "Discuss project requirements",
    },
  ],
  "2025-04-03": [
    {
      id: "5",
      title: "Ads Campaign Nr/2",
      date: new Date(2025, 3, 3),
      startTime: "09:00",
      endTime: "17:00",
      color: "yellow",
      description: "AdSense + FB, Target Audience",
    },
    {
      id: "6",
      title: "Design Review",
      date: new Date(2025, 3, 3),
      startTime: "11:00",
      endTime: "12:00",
      color: "purple",
      description: "Review new UI designs",
    },
    {
      id: "7",
      title: "Product Demo",
      date: new Date(2025, 3, 3),
      startTime: "15:00",
      endTime: "16:00",
      color: "red",
      description: "Demo new features to stakeholders",
    },
    {
      id: "8",
      title: "Marketing Meeting",
      date: new Date(2025, 3, 3),
      startTime: "16:30",
      endTime: "17:30",
      color: "green",
      description: "Discuss Q2 marketing strategy",
    },
  ],
  "2025-04-04": [
    {
      id: "9",
      title: "Ads Campaign Nr/2",
      date: new Date(2025, 3, 4),
      startTime: "09:00",
      endTime: "17:00",
      color: "yellow",
      description: "AdSense + FB, Target Audience",
    },
    {
      id: "10",
      title: "Team Lunch",
      date: new Date(2025, 3, 4),
      startTime: "12:00",
      endTime: "13:30",
      color: "blue",
      description: "Team building lunch",
    },
  ],
  "2025-04-05": [
    {
      id: "11",
      title: "Ads Campaign Nr/2",
      date: new Date(2025, 3, 5),
      startTime: "09:00",
      endTime: "17:00",
      color: "yellow",
      description: "AdSense + FB, Target Audience",
    },
    {
      id: "12",
      title: "Weekend Planning",
      date: new Date(2025, 3, 5),
      startTime: "16:00",
      endTime: "17:00",
      color: "green",
      description: "Plan weekend activities",
    },
  ],
  "2025-04-06": [
    {
      id: "13",
      title: "All-Day Project Sprint",
      date: new Date(2025, 3, 6),
      startTime: "09:00",
      endTime: "23:30",
      color: "red",
      description: "Intensive project sprint",
      allDay: true,
    },
  ],
  "2025-04-09": [
    {
      id: "14",
      title: "International Client Meeting",
      date: new Date(2025, 3, 9),
      startTime: "03:00",
      endTime: "04:00",
      color: "green",
      description: "Meeting with international client",
    },
    {
      id: "15",
      title: "Team Lunch",
      date: new Date(2025, 3, 9),
      startTime: "12:00",
      endTime: "13:30",
      color: "blue",
      description: "Team building lunch",
    },
  ],
  "2025-04-10": [
    {
      id: "16",
      title: "Workshop A",
      date: new Date(2025, 3, 10),
      startTime: "14:00",
      endTime: "16:00",
      color: "purple",
      description: "Technical workshop",
    },
    {
      id: "17",
      title: "Product Planning",
      date: new Date(2025, 3, 10),
      startTime: "10:00",
      endTime: "11:30",
      color: "green",
      description: "Plan product roadmap",
    },
    {
      id: "18",
      title: "Marketing Review",
      date: new Date(2025, 3, 10),
      startTime: "16:30",
      endTime: "17:30",
      color: "yellow",
      description: "Review marketing performance",
    },
  ],
  "2025-04-12": [
    {
      id: "19",
      title: "Product Development Review",
      date: new Date(2025, 3, 12),
      startTime: "01:00",
      endTime: "05:00",
      color: "purple",
      description: "Review product development progress",
    },
  ],
  "2025-04-15": [
    {
      id: "20",
      title: "Investor Presentation",
      date: new Date(2025, 3, 15),
      startTime: "06:30",
      endTime: "08:00",
      color: "yellow",
      description: "Present to potential investors",
    },
    {
      id: "21",
      title: "Team Lunch",
      date: new Date(2025, 3, 15),
      startTime: "12:00",
      endTime: "13:30",
      color: "blue",
      description: "Team building lunch",
    },
  ],
  "2025-04-17": [
    {
      id: "22",
      title: "Team Breakfast",
      date: new Date(2025, 3, 17),
      startTime: "07:00",
      endTime: "08:30",
      color: "blue",
      description: "Team breakfast meeting",
    },
  ],
  "2025-04-19": [
    {
      id: "23",
      title: "Asia Market Review",
      date: new Date(2025, 3, 19),
      startTime: "01:00",
      endTime: "03:00",
      color: "green",
      description: "Review Asian market performance",
    },
    {
      id: "24",
      title: "Team Standup",
      date: new Date(2025, 3, 19),
      startTime: "09:30",
      endTime: "10:00",
      color: "blue",
      description: "Daily team standup",
    },
    {
      id: "25",
      title: "Client Call",
      date: new Date(2025, 3, 19),
      startTime: "11:00",
      endTime: "12:00",
      color: "purple",
      description: "Call with client to discuss progress",
    },
    {
      id: "26",
      title: "Product Demo",
      date: new Date(2025, 3, 19),
      startTime: "14:00",
      endTime: "15:00",
      color: "red",
      description: "Demo new features",
    },
    {
      id: "27",
      title: "Marketing Meeting",
      date: new Date(2025, 3, 19),
      startTime: "15:30",
      endTime: "16:30",
      color: "yellow",
      description: "Discuss marketing strategy",
    },
  ],
  "2025-04-20": [
    {
      id: "28",
      title: "Early Strategy Meeting",
      date: new Date(2025, 3, 20),
      startTime: "02:00",
      endTime: "04:00",
      color: "purple",
      description: "Early morning strategy session",
    },
    {
      id: "29",
      title: "Team Lunch",
      date: new Date(2025, 3, 20),
      startTime: "12:00",
      endTime: "13:30",
      color: "blue",
      description: "Team building lunch",
    },
    {
      id: "30",
      title: "Client Call",
      date: new Date(2025, 3, 20),
      startTime: "15:00",
      endTime: "16:00",
      color: "green",
      description: "Follow-up with client",
    },
  ],
  "2025-04-22": [
    {
      id: "31",
      title: "Product Launch",
      date: new Date(2025, 3, 22),
      startTime: "10:00",
      endTime: "12:00",
      color: "red",
      description: "Launch new product",
    },
    {
      id: "32",
      title: "Marketing Campaign",
      date: new Date(2025, 3, 22),
      startTime: "14:00",
      endTime: "16:00",
      color: "yellow",
      description: "Kick off marketing campaign",
    },
  ],
  "2025-04-24": [
    {
      id: "33",
      title: "Conference A",
      date: new Date(2025, 3, 24),
      startTime: "12:00",
      endTime: "15:00",
      color: "green",
      description: "Attend industry conference",
    },
    {
      id: "34",
      title: "Team Standup",
      date: new Date(2025, 3, 24),
      startTime: "09:30",
      endTime: "10:00",
      color: "blue",
      description: "Daily team standup",
    },
  ],
  "2025-04-25": [
    {
      id: "35",
      title: "Training Session",
      date: new Date(2025, 3, 25),
      startTime: "14:00",
      endTime: "17:00",
      color: "purple",
      description: "Team training session",
    },
  ],
  "2025-04-28": [
    {
      id: "36",
      title: "Board Meeting",
      date: new Date(2025, 3, 28),
      startTime: "15:00",
      endTime: "17:00",
      color: "blue",
      description: "Quarterly board meeting",
    },
    {
      id: "37",
      title: "Team Lunch",
      date: new Date(2025, 3, 28),
      startTime: "12:00",
      endTime: "13:30",
      color: "green",
      description: "Team building lunch",
    },
  ],
}
